### ISSUE TITLE
Same CSS prop repeated in different class attributes.

### ISSUE THREAD

**Issue by soujvnunes** [soujvnunes/ufal-60-anos#132]
Instead of:
```css
.class {
  box-sizing: inherit;
  color: black;
}
.another-class {
  background-color: white;
  color: black;
}
```
_usage_
```jsx
<div class="class another-class" />
```

do:
```css
.color-black {
  color: black;
}
.class {
  box-sizing: inherit;
}
.another-class {
  background-color: white;
}
```
_usage_
```jsx
<div class="color-black class another-class" />
```

Motive: this enhances performance when aligned with other good front-end development practices. Do not use tools as styled-components since it still do not group classes with its assigned prop CSS style.

PS.: Pre-define some classes as utils with its prop values as `var`, ie. `color: var(--color)`, to improve the maintability in some level since use CSS this way is hard to do it.
